### ISSUE TITLE
Cerebroretinal vasculopathy (Orphanet:3421) obsoletion status

### ISSUE THREAD

**Issue by cmungall** [Orphanet/ORDO#1]
Hello @Orphanet 

I am wondering about the status of obsolete classes in ORDO, in particular the status of Grand Kaine Fulling vs Cerebroretinal vasculopathy. My understanding is the orpha website is frequently updated, and the ORDO ontology is released every 6 months. Thus ORDO should lag behind the website

The page for "Cerebroretinal vasculopathy"
http://www.orpha.net/consor/cgi-bin/OC_Exp.php?Expert=3421
is active. It lists Grand-Kaine-Fulling syndrome as a synonym, and a xref to GARD [2558](https://rarediseases.info.nih.gov/diseases/2558/index). There is no indication that this is obsolete

However, the OLS view of ORDO for this ID (http://www.orpha.net/ORDO/Orphanet_3421 ) shows this as being obsolete, with a replacement of http://www.orpha.net/ORDO/Orphanet_247691
![image](https://user-images.githubusercontent.com/50745/36068256-c0cd7f88-0e85-11e8-9fc6-523e7184a392.png)

The replacement class has no history of the previous name or synonyms or IDs.

Is there a reason it is obsolete in ORDO and not on the website? If ORDO is behind the website, it means either the class has become unobsoleted, or the website doesn't show obsoletion status? Or are the two out of sync in some other way.

Also it's useful if the obsolete class does not lose all of the original properties, and if a reason for obsolescence is stated. If someone searches ORDO for the concept "Grand-Kaine-Fulling syndrome" or "Cerebroretinal vasculopathy" (https://www.ncbi.nlm.nih.gov/pubmed/3174024) they can be directed to the appropriate concept and understand why

**Comment by Orphanet** [comment]
Thanks for your feedback.
The website is updated on very regular basis. The page for "Cerebroretinal vasculopathy"
http://www.orpha.net/consor/cgi-bin/OC_Exp.php?Expert=3421 is active and you have the information about  that disease which has been moved to Retinal vasculopathy with cerebral leukoencephalopathy and systemic manifestations. (and you won't have any experts resources linked to such obsoleted disease)
So, yes, a concept will be obsoleted first in the website before ORDO. 
However, in the website the obsolescence maybe unclear and keeping some properties is useful in the ontology, I forward your remarks to the diseases team.

**Comment by cmungall** [comment]
Apologies, I did not see the link to the replacement term! But maybe other users are as unobservant as I am, it might be good to make the status clearer.

Anyway, that explains that part - in this case the two are in sync, it's just a matter of presentation.

Yes, if the original properties were either transferred to the replacement class (if appropriate) or preserved on the obsoleted class in ORDO this would be helpful.
