### ISSUE TITLE
Suggest revising def for Orphanet:1866 'focal, segmental or multifocal dystonia'

### ISSUE THREAD

**Issue by nicolevasilevsky** [Orphanet/ORDO#10]
The text def for 'focal, segmental or multifocal dystonia' does not match the label:

Focal Dystonia is a rare neurologic movement disorder characterized by sustained muscle contractions of a single body region, usually producing twisting and repetitive movements or abnormal postures or positions.

It does not define segmental or multifocal dystonia.

Related to https://github.com/monarch-initiative/mondo/issues/229

**Comment by nicolevasilevsky** [comment]
@Orphanet

**Comment by ana-rath-orphanet** [comment]
a rare neurologic movement disorder characterized by sustained muscle contractions of a single body region, usually producing twisting and repetitive movements or abnormal postures or positions.

**Comment by nicolevasilevsky** [comment]
Thanks @ana-rath-orphanet!
