### ISSUE TITLE
typo in Autosomal dominant complex spastic paraplegia type 9B?

### ISSUE THREAD

**Issue by nicolevasilevsky** [Orphanet/ORDO#8]
Orphanet has this disease: Autosomal dominant complex spastic paraplegia type 9B

It seems there are two types of SPG that are caused by ALDH18A1:
SPG9A, which is autosomal dominant
SPG9B, which is autosomal recessive

Could this AD-SPG9B be a typo? Our team could not find any evidence of a AD-SPG9B in the literature.

cc @cmungall

**Comment by nicolevasilevsky** [comment]
@davidlagorce pinging you about this, thanks!

**Comment by caterina-lucano-orphanet** [comment]
Hi @nicolevasilevsky, I am Caterina, the scientific team manager at Orphanet. David forwarded your question to me. Indeed, this is not a typo, as Orphanet has two types of SPG9B in the database: ORPHA:447757 Autosomal dominant spastic paraplegia type 9B and ORPHA:447760 Autosomal recessive spastic paraplegia type 9B. Both were created based on Coutelier et al. 2015 (PMID:26026163).

At that time AD-SPG9B was described in 3 independent families (Italy, France) + 2 sporadic patients (USA, Australia/UK). Onset: adolescent, adult. It was estimated to be a predominantly pure HSP characterized by slowly progressive spastic paraparesis, gait disturbances, upper motor neuron signs, sensory impairment and pes cavus in some patients, and normal cognition.

AR-SPG9B on the other hand as an onset in infancy and childhood. It is a complex HSP with slowly progressive spastic paraparesis, upper motor signs, pseudobulbar palsy, urinary incontinence, skeletal anomalies, cerebellar signs (tremor in 30%), progressive cognitive impairment.

At the time of creation, AD-SPG9B was considered by the Orphanet information scientists a clinical entity sufficiently distinct from AD-SPG9A, that was instead created based on Seri et al. 1999 (PMID 9973297) and Slavotinek et al. 1996, (PMID: 8779323), and was described in 2 independent families (Italian, British). Onset: Infancy, Adolescent, Adult. It was estimated to be a complex HSP characterized by congenital bilateral cataracts with motor neuropathy, persistent vomiting, short stature, skeletal abnormalities (growth impairment, pes cavus), muscle wasting (hands and forelegs), and variable spastic paraparesis with incomplete penetrance.

This representation is also in line with the description by the Neuromuscular Disease Center (Washington University, St. Louis, MO, USA) that can be found at: https://neuromuscular.wustl.edu/spinal/fsp.html#aldh18a1

This said, I agree with you on the fact that this representation might be outdated and might not reflect the current state of knowledge presented in the literature. At the moment, we do not have the capacity to perform a much-needed systematic review of the spastic paraplegias entries in Orphanet, but we will plan this task in the future together with the appropriate network of experts.

I hope this solves your doubts and gives you a bit more insight into why we do have this entity in Orphanet. Please let me know if you need more info on this!

Caterina

**Comment by nicolevasilevsky** [comment]
This is very helpful, thanks Caterina! I will close this ticket.
